-- Fresh installations only: 20 MCQs + 2 descriptive tasks, 100 points.
-- Existing installations must use migration 006 instead of rerunning this file.
insert into public.questions
(id, category, type, question_text, code_snippet, options, correct_answer, points, difficulty, is_active, sort_order, evaluation_notes)
values
('00600000-0000-4000-8000-000000000001', 'python_programming', 'code_output', 'What does this code print?', 'a = [1, 2]
b = a
b.append(3)
print(len(a), a[-1])', '["2 2", "3 3", "2 3", "3 2"]'::jsonb, '3 3', 4, 'easy', true, 1, 'b and a refer to the same list. append changes that list to [1, 2, 3], so its length and last element are both 3.'),
('00600000-0000-4000-8000-000000000002', 'python_programming', 'code_output', 'What is the output of this slice?', 'word = "APPEX"
print(word[1:4])', '["APP", "PEX", "PP", "PPE"]'::jsonb, 'PPE', 4, 'easy', true, 2, 'Python slices include the start index and exclude the stop index. Positions 1, 2, and 3 are P, P, and E.'),
('00600000-0000-4000-8000-000000000003', 'python_programming', 'code_output', 'What value is printed after the loop?', 'total = 0
for n in range(1, 6):
    if n % 2 != 0:
        continue
    total += n
print(total)', '["6", "9", "15", "12"]'::jsonb, '6', 4, 'medium', true, 3, 'range(1, 6) visits 1 through 5. Odd values skip the addition; only 2 and 4 are added.'),
('00600000-0000-4000-8000-000000000004', 'python_programming', 'code_output', 'What does this dictionary code print?', 'counts = {"a": 2}
counts["b"] = counts.get("b", 0) + 1
print(counts.get("a", 0) + counts["b"])', '["1", "2", "3", "4"]'::jsonb, '3', 4, 'medium', true, 4, 'Missing key b defaults to 0 and is incremented to 1. Existing key a stays 2. The printed sum is 3.'),
('00600000-0000-4000-8000-000000000005', 'computer_technology', 'mcq', 'Which statement is true when you save a file to an SSD and shut down your laptop?', null, '["Both remain in RAM until the next restart", "The document remains on the SSD; the app’s RAM contents are lost", "The document moves into RAM; the app’s state stays on the SSD automatically", "Both are lost unless the laptop stays plugged in"]'::jsonb, 'The document remains on the SSD; the app’s RAM contents are lost', 4, 'easy', true, 5, 'An SSD is nonvolatile storage; ordinary RAM is volatile. Saving the document persists it, but does not automatically persist all application working memory.'),
('00600000-0000-4000-8000-000000000006', 'computer_technology', 'mcq', 'A website opens using its IP address, but not its name. Which tool should you use first to check how the name is translated into an IP address?', null, '["Measure download speed using the IP address", "Check the laptop’s available RAM", "Reinstall the browser before checking the address", "Look up that hostname using a DNS lookup tool"]'::jsonb, 'Look up that hostname using a DNS lookup tool', 4, 'easy', true, 6, 'A DNS lookup tests the hostname-to-address mapping directly. IP connectivity and general browser access are already partly established. A lookup can reveal an incorrect or missing DNS result; it does not prove every other part of the site works.'),
('00600000-0000-4000-8000-000000000007', 'computer_technology', 'mcq', 'An API returns HTTP 404 (not found). What should you check first?', null, '["Compare the requested path and resource ID with the API’s defined routes", "Increase the request timeout to allow more processing", "Check whether the request exceeded the server’s rate limit", "Check whether the server’s disk has enough free space"]'::jsonb, 'Compare the requested path and resource ID with the API’s defined routes', 4, 'easy', true, 7, '404 indicates that the requested resource was not found. Route/path and resource-ID checks address that meaning most directly; a timeout, rate limit, or disk failure would not explain 404 by itself.'),
('00600000-0000-4000-8000-000000000008', 'computer_technology', 'mcq', 'Your website uses a secret database key. Where should code using this key run so visitors cannot see it?', null, '["In browser JavaScript with the key Base64-encoded", "In browser JavaScript loaded only after login", "On a server endpoint that checks access and keeps the key server-side", "In a public environment variable with a difficult-to-guess name"]'::jsonb, 'On a server endpoint that checks access and keeps the key server-side', 4, 'medium', true, 8, 'Browser-delivered keys can be inspected regardless of encoding, login gating, or variable names. Keep the key server-side and authorize each request; a server endpoint alone is insufficient without access checks.'),
('00600000-0000-4000-8000-000000000009', 'aptitude_patterns', 'mcq', 'Two volunteers pack 10 kits in one hour. At the same rate per person, how many kits can four volunteers pack in one hour?', null, '["10", "20", "30", "40"]'::jsonb, '20', 4, 'easy', true, 9, 'Doubling the volunteers doubles output at the stated constant rate: 10 × 2 = 20.'),
('00600000-0000-4000-8000-000000000010', 'aptitude_patterns', 'mcq', 'The numbers increase by 3 each time: 4, 7, 10, 13. What comes next?', null, '["14", "15", "17", "16"]'::jsonb, '16', 4, 'easy', true, 10, 'Add 3 to 13 to get 16.'),
('00600000-0000-4000-8000-000000000011', 'aptitude_patterns', 'mcq', 'All trial accounts are blocked from publishing. A club account is a trial account. What must be true?', null, '["That club account cannot publish", "Every club account is a trial account", "That club account can publish once", "All accounts are blocked from publishing"]'::jsonb, 'That club account cannot publish', 4, 'easy', true, 11, 'The stated rule applies to this account because it is a trial account.'),
('00600000-0000-4000-8000-000000000012', 'aptitude_patterns', 'mcq', 'A bag contains 3 blue tokens and 2 red tokens. You draw one token randomly. What is the probability of drawing blue?', null, '["1/5", "2/5", "3/5", "1/2"]'::jsonb, '3/5', 4, 'easy', true, 12, 'Three of the five tokens are blue, so the probability is 3/5.'),
('00600000-0000-4000-8000-000000000013', 'situational_decision', 'scenario_mcq', 'Your demo is due in 30 minutes. Login works. Export needs 10 minutes to finish and 10 minutes to test. An optional chart needs 40 minutes. Which plan fits the deadline?', null, '["Spend 15 minutes on the chart, then finish export and its testing in the remaining time", "Finish and test export, freeze the chart, and use the remaining time for a rehearsal", "Spend 30 minutes on the chart, then demonstrate export using the unfinished version", "Spend 20 minutes on the chart and 10 on export, skipping export testing"]'::jsonb, 'Finish and test export, freeze the chart, and use the remaining time for a rehearsal', 4, 'easy', true, 13, 'Export work plus its required testing takes 20 minutes, leaving 10 for rehearsal. The optional chart cannot be completed within the available time. The correct plan satisfies mandatory scope without dropping validation.'),
('00600000-0000-4000-8000-000000000014', 'situational_decision', 'scenario_mcq', 'Task A takes 10 minutes. Task B takes 20 minutes and must wait for A to finish. Another volunteer can do task C (15 minutes) at the same time as A. How soon can all three tasks finish?', null, '["20 minutes", "25 minutes", "45 minutes", "30 minutes"]'::jsonb, '30 minutes', 4, 'easy', true, 14, 'A followed by B takes 30 minutes. C finishes after 15 minutes in parallel, so all tasks finish after 30 minutes.'),
('00600000-0000-4000-8000-000000000015', 'situational_decision', 'scenario_mcq', 'Visitors open your signup page but leave without completing it. You do not know why. Which action best helps you find the problem?', null, '["Observe a few visitors attempting signup and record the step where they get stuck", "Change the page colors and compare total visits immediately", "Add more required fields to learn more about visitors", "Ask the team to vote on the most attractive replacement layout"]'::jsonb, 'Observe a few visitors attempting signup and record the step where they get stuck', 4, 'medium', true, 15, 'A short observed task provides direct evidence of the point of difficulty. Visits alone do not identify signup friction, extra fields change the problem, and team preferences are not observations of visitor behavior. This is diagnostic evidence, not a statistically conclusive experiment.'),
('00600000-0000-4000-8000-000000000016', 'situational_decision', 'scenario_mcq', 'A room holds 40 people. You need to give 80 people a one-hour workshop, and have the room for two hours. There is no setup gap. Which plan works?', null, '["Three sessions of 30, 30, and 20 attendees, each lasting 1 hour", "Four 20-person sessions of 30 minutes each", "Two 40-person sessions of 1 hour each", "One 80-person session lasting 2 hours"]'::jsonb, 'Two 40-person sessions of 1 hour each', 4, 'easy', true, 16, 'Two back-to-back one-hour sessions provide 80 complete attendee-hours while occupancy never exceeds 40. Three one-hour sessions need three hours. Half-hour sessions do not meet the uninterrupted one-hour requirement; one 80-person session exceeds capacity.'),
('00600000-0000-4000-8000-000000000017', 'commitment_reliability', 'scenario_mcq', 'A report is due today. Attendance is verified, but survey results are not ready. The sponsor accepts a partial report. What should you send?', null, '["Send verified attendance totals and present provisional survey estimates as final results", "The verified totals, clearly marked pending survey results, and a follow-up time", "Hold the entire report until surveys are checked and propose a follow-up after today’s deadline", "Send verified attendance totals and mark the unchecked survey section complete without figures"]'::jsonb, 'The verified totals, clearly marked pending survey results, and a follow-up time', 4, 'easy', true, 17, 'The sponsor explicitly permits a labeled partial report. Share verified facts, identify pending results, and commit to a follow-up. Presenting estimates as final or marking an unchecked section complete misrepresents certainty. Holding the entire report misses today’s deadline despite the permitted partial delivery.'),
('00600000-0000-4000-8000-000000000018', 'commitment_reliability', 'scenario_mcq', 'You have one hour left, but two assigned tasks each need one hour. You cannot delegate and do not know which is more important. What should you do first?', null, '["Split the hour equally between the two tasks and mark both complete despite unfinished work", "Start the newer task and reserve the last five minutes to explain why the older one is unfinished", "Start the older task and tell the lead about the newer one only if someone asks after the deadline", "Tell the lead the time conflict now and agree which task to finish and when to deliver the other"]'::jsonb, 'Tell the lead the time conflict now and agree which task to finish and when to deliver the other', 4, 'medium', true, 18, 'Available capacity cannot satisfy both tasks. Clarify priority and renegotiate the other delivery before the deadline. Do not claim partial tasks are complete or silently invent priority when the lead can resolve it.'),
('00600000-0000-4000-8000-000000000019', 'wildcard', 'scenario_mcq', 'You want to find out whether a new display location attracts more visitors. What should you keep the same to make the comparison fair?', null, '["The poster and observation time, with similar visitor flow", "Neither the poster nor the observation time", "Only the display name; change everything else", "The location; compare two different posters"]'::jsonb, 'The poster and observation time, with similar visitor flow', 4, 'medium', true, 19, 'Keeping the poster and observation time the same, with similar visitor flow, helps isolate the effect of location.'),
('00600000-0000-4000-8000-000000000020', 'wildcard', 'scenario_mcq', 'Before building an app, you want to check whether people understand its instructions. Which quick test is most useful?', null, '["A poster asking visitors whether they would like the finished app", "A spreadsheet forecasting how many people will use it", "Paper screens with the actual instructions; ask visitors to complete the intended task", "A slide listing every feature planned for the final app"]'::jsonb, 'Paper screens with the actual instructions; ask visitors to complete the intended task', 4, 'easy', true, 20, 'Task completion with the actual instructions directly tests comprehension within the available resources. Interest, usage forecasts, and feature descriptions answer different questions. The paper prototype validates instructions, not all aspects of the finished app.'),
('00600000-0000-4000-8000-000000000021', 'situational_decision', 'short_text', 'Plan a 60-minute APPEX workshop for 20 students tomorrow. You have ₹1,000, two volunteers, five shared laptops, and unreliable Wi-Fi. Briefly explain: (1) a simple activity and session schedule, (2) how you divide the work and share laptops, and (3) how you use the budget. Include one backup plan and how you would tell whether the workshop went well.', null, null, null, 10, 'easy', true, 21, 'Score holistically out of 10. Look for a simple activity that fits 60 minutes, clear volunteer roles, sensible laptop sharing (for example, four students per laptop), spending within ₹1,000, a useful backup for Wi-Fi or staffing, and a basic success check. Accept varied activities and sensible tradeoffs. 1–3: vague or misses major constraints. 4–6: workable plan with gaps. 7–8: clear and covers most constraints. 9–10: realistic, coherent plan with useful backup and success check. Award 0 for no meaningful answer. Do not reward length alone.'),
('00600000-0000-4000-8000-000000000022', 'improvisation_problem_solving', 'short_text', 'Your app demo works on your laptop but fails on the presentation laptop. You have 15 minutes before presenting, and the error only says “request failed”. A teammate is waiting for your API. Explain: (1) two quick checks you would try and what each result tells you, (2) how you and your teammate split the work, and (3) a backup if the problem is not fixed in time. What would you tell the audience?', null, null, null, 10, 'medium', true, 22, 'Score holistically out of 10. Look for two useful checks with interpreted results (for example, network access and API address/configuration), a practical work split that unblocks the teammate, a time limit on debugging, an achievable fallback such as the working laptop, mock/offline data or a recording, and honest audience communication. The cause is not known; accept defensible checks. 1–3: unsupported guesses or vague steps. 4–6: useful checks and a basic backup with gaps. 7–8: clear checks, work split and fallback. 9–10: coherent plan connecting outcomes, time, teammate needs and communication. Award 0 for no meaningful answer.')
on conflict (id) do nothing;
